### ISSUE TITLE
自动重定向是怎么实现的

### ISSUE THREAD

**Issue by mmdjiji** [fslongjin/This-repo-has-547-stars#10]
例如现在的star数是352而url为 `https://github.com/fslongjin/This-repo-has-352-stars` ，而当我访问 `https://github.com/fslongjin/This-repo-has-123-stars` 时链接会被自动重定向到当前仓库。这是很神奇的因为我们都知道，通常当访问一个不存在的仓库时，会发生404错误。

除此之外我注意到如果访问一个未来的star数量则不会重定向而是发生404，例如 `https://github.com/fslongjin/This-repo-has-1024-stars` 。

对原理非常好奇，故提此issue，望不吝赐教。

**Comment by fslongjin** [comment]
哈哈哈，这个应该是GitHub自带的功能，当你修改仓库的名字之后，旧的仓库的链接会被重定向到新的链接上。

**Comment by mmdjiji** [comment]
哦哦，我最开始也是这么猜测的，只是当时觉得GitHub不会存那么多history，不会把前面几百个历史名字全存下吧。

感谢。
